### ISSUE TITLE
Changer les couleurs des mot-clés pour mieux les distinguer

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/conferences#11]

**Comment by benoit-philha** [comment]
J'ai modifié les couleurs dans les xml, mais Marie devrait attribuer des couleurs aux différents types d'onglets directement dans le html. J'ai fait plusieurs tests pour le rendu des couleurs, selon la composition du nuage. j'ai encore quelques doutes sur certaines couleurs. Je vais essayer de faire un post avec des liens.
