### ISSUE TITLE
Conférence John Cage - Mot Clé Pierre Boulez tourne en boucle ( ne démarre pas )

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/conferences#14]
Voir avec Marie si c'est un problème qu'elle peut régler

**Comment by marie-ototoi** [comment]
Duplicate #7
quand vous reportez un problème spécifique pensez à mettre le lien dans la description ça fait gagner plein de temps !
http://education.citedelamusique.fr/conferences/index.aspx?id=0998324
