### ISSUE TITLE
Changer le Title de la page HTML qui contient le player

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/conferences#15]
Mettre le titre de la conférence suivit de " - Philharmonie de Paris"

**Comment by marie-ototoi** [comment]
pour David

**Comment by ddenocq** [comment]
Le titre de la conférence est ajouté dans le title suivi de  " - Philharmonie de Paris".
Une "fausse" page d'accueil est ajoutée listant l'ensemble des conférences disponibles : 
http://education.citedelamusique.fr/conferences
