### ISSUE TITLE
Renommage Picto (titre en Hover - Tracks / Keywords / description)

### ISSUE THREAD

**Issue by smazet** [philharmoniedeparis/conferences#19]
Il faudrait certainement changer les titres des pictos en état hover.

Chapitre ? Chapitrages ? Playlist ?
Mots-clés ? Sujets ? thèmes ?

**Comment by benoit-philha** [comment]
Je ne suis pas certain du meilleur nom à attribuer, je fais donc plusieurs propositions pour chacun et je pense que Rodolphe pourra trancher =
1- Sommaire / Plan / Chapitres
2- Index / Mots-Clés
3- Présentation / Informations

**Comment by marie-ototoi** [comment]
En attendant mieux :
- Chapitres
- Index
- Présentation
