### ISSUE TITLE
Timeline / Distinguer parties et sous-parties selon l'emplacement du curseur

### ISSUE THREAD

**Issue by smazet** [philharmoniedeparis/conferences#20]
Peut-on reprendre la proposition du player rond.
C'est à dire : n'afficher que les parties principales, mais lorsque le curseur passe dans les parties on peut voir l'ensemble des sous parties qui la compose.

Pour faciliter la lecture... 

Proposition à retenir. Ou pas !

**Comment by marie-ototoi** [comment]
les sous-parties ne font que la moitié de la timeline
