### ISSUE TITLE
Bug démarrage

### ISSUE THREAD

**Issue by benoit-philha** [philharmoniedeparis/conferences#25]
Conf : Le wagnérisme en France :+1: http://education.citedelamusique.fr/conferences/index.aspx?id=0826711

Mot clé "Guy de Pourtalès et généralement toute la fin de la conf. ne s'ouvrent pas. Constaté sur firefox et chrome, ainsi que sur le poste de Sarah.

**Comment by marie-ototoi** [comment]
Duplicate #7
