### ISSUE TITLE
Attribuation d'un numéro à chaque catégorie d'onglet

### ISSUE THREAD

**Issue by benoit-philha** [philharmoniedeparis/conferences#26]
Cette atribution doit permettre d'attribuer des codes couleurs à chaque onglet. Attention à bien rendre possible le fait de n'avoir que certains onglets (par ex. à l'heure actuelle, il est impossible d'avoir un 1 ; 2; 3; 5 ; sans avoir de 4). la possibilité également de les mettre dans l'ordre que l'on souhaite serait très pratique.
Proposition
Tout = 0
Thèmes = 1
Personnes = 2
Instruments = 3
Oeuvres = 4
Intervenants = 5
Facteurs = 6
Lieux = 7
Concert = 8
Animaux = 9
Techniques de jeu = 10
Autres = 11....

**Comment by marie-ototoi** [comment]
Duplicate #11

**Comment by marie-ototoi** [comment]
finalement dans le xml ce sera

type="tout"
type="themes"
type="personnes"
type="instruments"
type="oeuvres"
type="intervenants"
type="facteurs"
type="lieux"
type="concert"
type="animaux"
type="techniquesdejeu"

**Comment by benoit-philha** [comment]
Codes couleurs actuellement utilisés =
Tout > color="686868"
Thèmes > color="3b85bc"
Personnes > color="e5570a"
Instruments > color="7f0f8d"
Oeuvres > color="006f26"
Intervenants > color="808285"
Lieux, Facteurs.... > color="e10347" (à changer, un peu trop proche de Personnes > color="e5570a")
