### ISSUE TITLE
Contexte de lecture 

### ISSUE THREAD

**Issue by ddenocq** [philharmoniedeparis/conferences#32]
Quand un mots clé est selectionné, que l'utilisateur repasse sur la table des matières, la timeline affiche les zones liées au mot clé, mais celui-ci n'est pas affiché - indiqué.

Lors de l'écoute, si on suit la conférences du début à la fin les intervenants sont introduits, mais quand on clique sur une des pistes ou un mots clé on ne sais pas quel intervenant est en train de parler.

J'ai cliqué sur un titre, je déplace le curseur : le titre ayant le focus (bleu) ne correspond pas à ce que j'écoute.

**Comment by marie-ototoi** [comment]
J'ai réglé le problème du focus sur le titre. Je laisse le tiquet ouvert pour les autres suggestions. Si possible à l'avenir ouvrir un tiquet par suggestion ou bug.

**Comment by marie-ototoi** [comment]
on a ajouté le nom de l'intervenant dans l'affichage de la partie en cours sous la timeline
