### ISSUE TITLE
Lisibilité barre de lecture

### ISSUE THREAD

**Issue by benoit-philha** [philharmoniedeparis/conferences#45]
La différence entre les parties et les sous-parties est très difficile à percevoir dans la barre de lecture.
Utiliser du blanc pour séparer les parties ?

**Comment by smazet** [comment]
![test_blanc](https://cloud.githubusercontent.com/assets/11444189/6783849/64e7f55c-d17c-11e4-9377-035910c4acb1.PNG)

Petit test avec les séparations en blanc. C'est peut-être un peu plus lisible. Qu'en pensez-vous ?
