### ISSUE TITLE
Picto Extrait sonore

### ISSUE THREAD

**Issue by benoit-philha** [philharmoniedeparis/conferences#50]
Pour alléger les sommaires, remplacer la mention "extrait sonore :" par un picto ?
Type : deux croches ou autre ?

**Comment by benoit-philha** [comment]
![picto1](https://cloud.githubusercontent.com/assets/11444322/6897050/26b34f32-d6f1-11e4-9ef8-75a3fdb7c908.jpg)
![picto2](https://cloud.githubusercontent.com/assets/11444322/6897049/26b17874-d6f1-11e4-860c-06985a9fba7c.jpg)

**Comment by marie-ototoi** [comment]
cf xml de la conf 1029725

**Comment by marie-ototoi** [comment]
Mail Benoit 
Il y a un petit débat à propos du picto entre David, Sarah et moi.
David trouve que le picto rend la lecture difficile (trop lourd graphiquement), personnellement, je ne sais plus quoi en penser, je crois qu'en comparant, je trouve aussi que ça perturbe pas mal la hiérarchie visuelle des parties.
On se demande si le fait de rentrer le picto dans la ligne rendrait la hiérarchie plus "propre", en pièce jointe il y a une capture.
Nous ne sommes pas convaincu non plus....
 
Qu'en penses-tu ?


![picto_margin](https://cloud.githubusercontent.com/assets/1785024/6984745/8b21f76e-da2c-11e4-9cd2-b3fa569cd312.JPG)
