### ISSUE TITLE
Surbrillance des mots clés contextuels

### ISSUE THREAD

**Issue by benoit-philha** [philharmoniedeparis/conferences#51]
La surbrillance des mots-clés contextuels ne se fait plus comme avant avec l'encadré de couleur mais ils sont seulement soulignés. Seul le mot clé sélectionné est encadré.
Est-ce normal ?

**Comment by marie-ototoi** [comment]
c'est voulu, vu avec Rodolphe, mais on peut en rediscuter tous ensemble
