### ISSUE TITLE
Long au démarrage

### ISSUE THREAD

**Issue by benoit-philha** [philharmoniedeparis/conferences#7]
Bcp de mots-clés mettent plus de 30 sec à démarrer, voire ne démarrent pas.
- ex. Forum Asie Centrale (http://education.citedelamusique.fr/conferences/index.aspx?id=0950474), MC Thèmes : Nomade / Tengir-TOO.
- Cinéma en inde (http://education.citedelamusique.fr/conferences/index.aspx?id=0950562),
MC Thèmes : Diversité régionale

**Comment by marie-ototoi** [comment]
moi je ne l'ai pas constaté, ni chez moi, ni ici, sarah non plus, il faudrait tester sur un maximum de postes
